/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardsSkills: typeof import('./src/components/CardsSkills.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ImageProject: typeof import('./src/components/ImageProject.vue')['default']
    LinkSocialMedias: typeof import('./src/components/LinkSocialMedias.vue')['default']
    LinksSocialMedias: typeof import('./src/components/LinksSocialMedias.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    NavDrawer: typeof import('./src/components/NavDrawer.vue')['default']
    NavigationDrawer: typeof import('./src/components/NavigationDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextProject: typeof import('./src/components/TextProject.vue')['default']
  }
}
